//
$(document).ready(function(){
  $("#osugo-pic").click(function(){
    $("#osugo-desc").show();
    $("#osugo-icon").hide();
  });
  $("#osugo-desc").click(function(){
    $("#osugo-icon").show();
    $("#osugo-desc").hide();
  });
  $("#baraka-pic").click(function(){
    $("#baraka-desc").show();
    $("#baraka-icon").hide();
  });
  $("#baraka-desc").click(function(){
    $("#baraka-icon").show();
    $("#baraka-desc").hide();
  });$("#rita-pic").click(function(){
    $("#rita-desc").show();
    $("#rita-icon").hide();
  });
  $("#rita-desc").click(function(){
    $("#rita-icon").show();
    $("#rita-desc").hide();
  });
  $("#frank-pic").click(function(){
    $("#frank-desc").show();
    $("#frank-icon").hide();
  });
  $("#frank-desc").click(function(){
    $("#frank-icon").show();
    $("#frank-desc").hide();
  });
  $("#mike-pic").click(function(){
    $("#mike-desc").show();
    $("#mike-icon").hide();
  });
  $("#mike-desc").click(function(){
    $("#mike-icon").show();
    $("#mike-desc").hide();
  });
  $("#komen-pic").click(function(){
    $("#komen-desc").show();
    $("#komen-icon").hide();
  });
  $("#komen-desc").click(function(){
    $("#komen-icon").show();
    $("#komen-desc").hide();
  });
});
